/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerPenjualan;
import Koneksi.koneksi;
import Model.ModelPenjualan;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author Raihan
 */
public class FormPenjualan extends javax.swing.JFrame {
    private BigDecimal hargaBarang = BigDecimal.ZERO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPenjualan.class.getName());

    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan() {
        initComponents();
        tftotal.setEditable(false);
        try {

        MaskFormatter mf =
                new MaskFormatter("##/##/####");

        mf.install(tftanggal);

    } catch (Exception e) {
        e.printStackTrace();
    }

    tampilBarang();
    tampilMember();

    ControllerPenjualan controller =
            new ControllerPenjualan();

    controller.tampil(
            (DefaultTableModel) tbpenjualan.getModel()
    );

    tbpenjualan.addMouseListener(
            new java.awt.event.MouseAdapter() {

        public void mouseClicked(
                java.awt.event.MouseEvent evt) {

            tbpenjualanMouseClicked(evt);
        }
    });
    
    coidbarang.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        coidbarangActionPerformed(evt);
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfidpenjualan = new javax.swing.JTextField();
        coidbarang = new javax.swing.JComboBox<>();
        coidmember = new javax.swing.JComboBox<>();
        tfjumlah = new javax.swing.JTextField();
        tftotal = new javax.swing.JTextField();
        tftanggal = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpenjualan = new javax.swing.JTable();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btcetak = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Penjualan");

        jLabel2.setText("ID Penjualan");

        jLabel3.setText("ID Barang");

        jLabel4.setText("ID Member");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Total");

        jLabel7.setText("Tanggal Input");

        coidbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        coidmember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfjumlah.addActionListener(this::tfjumlahActionPerformed);
        tfjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfjumlahKeyReleased(evt);
            }
        });

        tftanggal.addActionListener(this::tftanggalActionPerformed);

        tbpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Penjualan", "ID Barang", "ID Member", "Jumlah", "Total", "Tanggal Input"
            }
        ));
        tbpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpenjualanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbpenjualan);

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        btcetak.setText("Cetak");
        btcetak.addActionListener(this::btcetakActionPerformed);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfidpenjualan)
                                    .addComponent(coidbarang, 0, 161, Short.MAX_VALUE)
                                    .addComponent(coidmember, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfjumlah)
                                    .addComponent(tftotal)
                                    .addComponent(tftanggal))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bttambah, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(btedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bthapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btcetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfidpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttambah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(coidbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btedit)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(coidmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bthapus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btreset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btcetak)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tftanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btkembali)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tftanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalActionPerformed

    private void btcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetakActionPerformed

    String hasil =
            "ID Penjualan : " + tfidpenjualan.getText()
            + "\nID Barang : " + coidbarang.getSelectedItem()
            + "\nID Member : " + coidmember.getSelectedItem()
            + "\nJumlah : " + tfjumlah.getText()
            + "\nTotal : " + tftotal.getText()
            + "\nTanggal : " + tftanggal.getText();

    JOptionPane.showMessageDialog(
            this,
            hasil,
            "Data Penjualan",
            JOptionPane.INFORMATION_MESSAGE
    );        // TODO add your handling code here:
    }//GEN-LAST:event_btcetakActionPerformed

    private void tbpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpenjualanMouseClicked
    int baris =
            tbpenjualan.getSelectedRow();

    tfidpenjualan.setText(
            tbpenjualan.getValueAt(
                    baris, 0
            ).toString()
    );

    coidbarang.setSelectedItem(
            tbpenjualan.getValueAt(
                    baris, 1
            ).toString()
    );

    coidmember.setSelectedItem(
            tbpenjualan.getValueAt(
                    baris, 2
            ).toString()
    );

    tfjumlah.setText(
            tbpenjualan.getValueAt(
                    baris, 3
            ).toString()
    );

    tftotal.setText(
            tbpenjualan.getValueAt(
                    baris, 4
            ).toString()
    );

    tftanggal.setText(
            tbpenjualan.getValueAt(
                    baris, 5
            ).toString()
    );
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpenjualanMouseClicked

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
    try {

        String tanggal =
                tftanggal.getText();

        String[] bagian =
                tanggal.split("/");

        String tanggalMysql =
                bagian[2] + "-" +
                bagian[1] + "-" +
                bagian[0];

        String barang =
                coidbarang.getSelectedItem().toString();

        int idBarang =
                Integer.parseInt(
                        barang.split(" - ")[0]
                );

        String member =
                coidmember.getSelectedItem().toString();

        int idMember =
                Integer.parseInt(
                        member.split(" - ")[0]
                );

        ModelPenjualan penjualan =
                new ModelPenjualan();

        penjualan.setId_penjualan(
                Integer.parseInt(
                        tfidpenjualan.getText()
                )
        );

        penjualan.setId_barang(idBarang);

        penjualan.setId_member(idMember);

        penjualan.setJumlah(
                Integer.parseInt(
                        tfjumlah.getText()
                )
        );

        penjualan.setTotal(
                new BigDecimal(
                        tftotal.getText()
                )
        );

        penjualan.setTgl_input(
                tanggalMysql
        );

        ControllerPenjualan controller =
                new ControllerPenjualan();

        controller.tambah(penjualan);

        controller.tampil(
                (DefaultTableModel)
                tbpenjualan.getModel()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal menambah data : "
                + e.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
    try {

        String tanggal =
                tftanggal.getText();

        String[] bagian =
                tanggal.split("/");

        String tanggalMysql =
                bagian[2] + "-" +
                bagian[1] + "-" +
                bagian[0];

        String barang =
                coidbarang.getSelectedItem().toString();

        int idBarang =
                Integer.parseInt(
                        barang.split(" - ")[0]
                );

        String member =
                coidmember.getSelectedItem().toString();

        int idMember =
                Integer.parseInt(
                        member.split(" - ")[0]
                );

        ModelPenjualan penjualan =
                new ModelPenjualan();

        penjualan.setId_penjualan(
                Integer.parseInt(
                        tfidpenjualan.getText()
                )
        );

        penjualan.setId_barang(idBarang);

        penjualan.setId_member(idMember);

        penjualan.setJumlah(
                Integer.parseInt(
                        tfjumlah.getText()
                )
        );

        penjualan.setTotal(
                new BigDecimal(
                        tftotal.getText()
                )
        );

        penjualan.setTgl_input(
                tanggalMysql
        );

        ControllerPenjualan controller =
                new ControllerPenjualan();

        controller.edit(penjualan);

        controller.tampil(
                (DefaultTableModel)
                tbpenjualan.getModel()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal mengubah data : "
                + e.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        int pilihan =
            JOptionPane.showConfirmDialog(
                    this,
                    "Yakin ingin menghapus data?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION
            );

    if(pilihan ==
            JOptionPane.YES_OPTION) {

        try {

            int idPenjualan =
                    Integer.parseInt(
                            tfidpenjualan.getText()
                    );

            ControllerPenjualan controller =
                    new ControllerPenjualan();

            controller.hapus(
                    idPenjualan
            );

            controller.tampil(
                    (DefaultTableModel)
                    tbpenjualan.getModel()
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
    tfidpenjualan.setText("");
    tfjumlah.setText("");
    tftotal.setText("");
    tftanggal.setText("");

    coidbarang.setSelectedIndex(0);
    coidmember.setSelectedIndex(0);

    tfidpenjualan.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        new FormUtama().setVisible(true);    
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    private void tfjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjumlahActionPerformed

    private void tfjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfjumlahKeyReleased
        hitungTotal();        // TODO add your handling code here:
    }//GEN-LAST:event_tfjumlahKeyReleased
    
    private void tampilBarang() {

    try {

        Connection cn =
                koneksi.getConnection();

        String sql =
                "SELECT id_barang,nama_barang FROM barang";

        ResultSet rs =
                cn.createStatement().executeQuery(sql);

        coidbarang.removeAllItems();

        while(rs.next()) {

            coidbarang.addItem(
                    rs.getString("id_barang")
                    + " - " +
                    rs.getString("nama_barang")
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}
    
    private void tampilMember() {

    try {

        Connection cn =
                koneksi.getConnection();

        String sql =
                "SELECT id_member,email FROM member";

        ResultSet rs =
                cn.createStatement().executeQuery(sql);

        coidmember.removeAllItems();

        while(rs.next()) {

            coidmember.addItem(
                    rs.getString("id_member")
                    + " - " +
                    rs.getString("email")
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}
    
    private void coidbarangActionPerformed(
        java.awt.event.ActionEvent evt) {

    try {

        String barang =
                coidbarang.getSelectedItem().toString();

        System.out.println("Combo = " + barang);

        int idBarang =
                Integer.parseInt(
                        barang.split(" - ")[0]
                );

        System.out.println("ID = " + idBarang);

        Connection cn =
                koneksi.getConnection();

        String sql =
                "SELECT harga_jual "
                + "FROM barang "
                + "WHERE id_barang=" + idBarang;

        ResultSet rs =
                cn.createStatement().executeQuery(sql);

        if(rs.next()){

            hargaBarang =
                    rs.getBigDecimal("harga_jual");

            System.out.println(
                    "Harga ditemukan = "
                    + hargaBarang
            );
        }

        hitungTotal();

    } catch(Exception e){

        e.printStackTrace();
    }
}
    
    private void hitungTotal(){

    try {

        int jumlah =
                Integer.parseInt(
                        tfjumlah.getText()
                );
        
        System.out.println("Harga Barang = " + hargaBarang);
        
        BigDecimal total =
                hargaBarang.multiply(
                        new BigDecimal(jumlah)
                );

        tftotal.setText(
                total.toString()
        );

    } catch(Exception e){

        tftotal.setText("");
    }
}
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPenjualan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcetak;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JComboBox<String> coidbarang;
    private javax.swing.JComboBox<String> coidmember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbpenjualan;
    private javax.swing.JTextField tfidpenjualan;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JFormattedTextField tftanggal;
    private javax.swing.JTextField tftotal;
    // End of variables declaration//GEN-END:variables
}
