/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerKategori;
import Model.ModelKategori;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Juan
 */
public class FormKategori extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKategori.class.getName());

    /**
     * Creates new form FormKategori
     */
    public FormKategori() {
        initComponents();

            try {
                MaskFormatter mf =
                        new MaskFormatter("##/##/####");

                mf.install(tftanggal);

            } catch (Exception e) {
                e.printStackTrace();
            }
            
            ControllerKategori controller =
            new ControllerKategori();

        controller.tampil(
            (DefaultTableModel) tbkategori.getModel()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfidkategori = new javax.swing.JTextField();
        tfnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tftanggal = new javax.swing.JFormattedTextField();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbkategori = new javax.swing.JTable();
        btkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Kategori");

        jLabel2.setText("ID Kategori");

        tfidkategori.addActionListener(this::tfidkategoriActionPerformed);

        jLabel3.setText("Nama Kategori");

        jLabel4.setText("Tanggal Input");

        tftanggal.addActionListener(this::tftanggalActionPerformed);

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        tbkategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Kategori", "Nama Kategori", "Tanggal Input"
            }
        ));
        tbkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbkategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbkategori);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfnama, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(tfidkategori)
                            .addComponent(tftanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfidkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tftanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bthapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btreset)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btkembali)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfidkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidkategoriActionPerformed

    private void tftanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
      try {

        String tanggal = tftanggal.getText();

        String[] bagian = tanggal.split("/");

        String tanggalMysql =
        bagian[2] + "-" +
        bagian[1] + "-" +
        bagian[0];

        ModelKategori kategori = new ModelKategori();

        kategori.setId_kategori(
                Integer.parseInt(tfidkategori.getText())
        );

        kategori.setNama_kategori(
                tfnama.getText()
        );

        kategori.setTgl_input(
                tanggalMysql
        );

        ControllerKategori controller =
                new ControllerKategori();

        controller.edit(kategori);

        controller.tampil(
                (DefaultTableModel) tbkategori.getModel()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
         // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
    int pilihan = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
    );

    if (pilihan == JOptionPane.YES_OPTION) {

        try {

            int id_kategori = Integer.parseInt(
                    tfidkategori.getText()
            );

            ControllerKategori controller = new ControllerKategori();

            controller.hapus(id_kategori);
            
             controller.tampil(
            (DefaultTableModel) tbkategori.getModel()
        );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }         // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        tfidkategori.setText("");
        tfnama.setText("");
        tftanggal.setText("");

        tfidkategori.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
            try {

        String tanggal = tftanggal.getText();

        String[] bagian = tanggal.split("/");

        String tanggalMysql =
        bagian[2] + "-" +
        bagian[1] + "-" +
        bagian[0];

        ModelKategori kategori = new ModelKategori();

        kategori.setId_kategori(
                Integer.parseInt(tfidkategori.getText())
        );

        kategori.setNama_kategori(
                tfnama.getText()
        );

        kategori.setTgl_input(
                tanggalMysql
        );

        ControllerKategori controller =
                new ControllerKategori();

        controller.tambah(kategori);

        controller.tampil(
                (DefaultTableModel) tbkategori.getModel()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        new FormUtama().setVisible(true);  
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    private void tbkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbkategoriMouseClicked
            int baris = tbkategori.getSelectedRow();

    tfidkategori.setText(
            tbkategori.getValueAt(baris, 0).toString()
    );

    tfnama.setText(
            tbkategori.getValueAt(baris, 1).toString()
    );

    String tanggalDb =
        tbkategori.getValueAt(baris, 2).toString();

        String[] bagian = tanggalDb.split("-");

        String tanggalForm =
                bagian[2] + "/" +
                bagian[1] + "/" +
                bagian[0];

        tftanggal.setText(tanggalForm);      // TODO add your handling code here:
    }//GEN-LAST:event_tbkategoriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKategori().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbkategori;
    private javax.swing.JTextField tfidkategori;
    private javax.swing.JTextField tfnama;
    private javax.swing.JFormattedTextField tftanggal;
    // End of variables declaration//GEN-END:variables
}
