/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerMember;
import Model.ModelMember;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class FormMember extends javax.swing.JFrame {
    
    private String pathGambar = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMember.class.getName());

    /**
     * Creates new form FormMember
     */
    public FormMember() {
        initComponents();
        
        ControllerMember controller =
            new ControllerMember();

        controller.tampil(
            (DefaultTableModel) tbmember.getModel()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfidmember = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        tftelepon = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        lbgambar = new javax.swing.JLabel();
        btgambar = new javax.swing.JButton();
        tfpath = new javax.swing.JTextField();
        tfnik = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmember = new javax.swing.JTable();
        btreset = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Member");

        jLabel2.setText("ID Member");

        jLabel3.setText("Alamat");

        jLabel4.setText("No Telepon");

        jLabel5.setText("Email");

        jLabel6.setText("Gambar");

        jLabel7.setText("NIK");

        lbgambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btgambar.setText("Tambah Gambar");
        btgambar.addActionListener(this::btgambarActionPerformed);

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        jButton2.setText("Edit");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        tbmember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Member", "Alamat", "No Telepon", "Email", "Gambar", "NIK"
            }
        ));
        tbmember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmember);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfemail)
                                    .addComponent(tftelepon)
                                    .addComponent(tfalamat)
                                    .addComponent(tfidmember)
                                    .addComponent(btgambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbgambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfnik)
                                    .addComponent(tfpath, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttambah, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(bthapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfidmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttambah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(bthapus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btreset))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btgambar)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(btkembali)
                                .addContainerGap())))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

        ModelMember member = new ModelMember();

        member.setId_member(
                Integer.parseInt(tfidmember.getText())
        );

        member.setAlamat_member(tfalamat.getText());
        member.setTelepon(tftelepon.getText());
        member.setEmail(tfemail.getText());
        member.setGambar(pathGambar);
        member.setNik(tfnik.getText());

        ControllerMember controller = new ControllerMember();

        controller.edit(member);
        
         controller.tampil(
            (DefaultTableModel) tbmember.getModel()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btgambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgambarActionPerformed
    JFileChooser chooser = new JFileChooser();
    int hasil = chooser.showOpenDialog(this);

if (hasil == JFileChooser.APPROVE_OPTION) {

    File file = chooser.getSelectedFile();

    String namaFile = file.getName();

    Path tujuan = Paths.get(
        "Foto_member/" + namaFile
);

        try {
        Files.createDirectories(
                Paths.get("Foto_member")
        );
            
            Files.copy(
                    file.toPath(),
                    tujuan,
                    StandardCopyOption.REPLACE_EXISTING
            );  } catch (IOException ex) {
            System.getLogger(FormMember.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    pathGambar = namaFile;

    tfpath.setText(pathGambar);

    ImageIcon icon =
            new ImageIcon(tujuan.toString());

    Image img = icon.getImage().getScaledInstance(
            lbgambar.getWidth(),
            lbgambar.getHeight(),
            Image.SCALE_SMOOTH
    );

    lbgambar.setIcon(
            new ImageIcon(img)
    );
}// TODO add your handling code here:
    }//GEN-LAST:event_btgambarActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        try {

        ModelMember member = new ModelMember();
        
        member.setId_member(Integer.parseInt(tfidmember.getText()));
        member.setAlamat_member(tfalamat.getText());
        member.setTelepon(tftelepon.getText());
        member.setEmail(tfemail.getText());
        member.setGambar(pathGambar);
        member.setNik(tfnik.getText());

        ControllerMember controller = new ControllerMember();
        controller.tambah(member);
        
        controller.tampil(
            (DefaultTableModel) tbmember.getModel()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
 
    int pilihan = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
    );

    if (pilihan == JOptionPane.YES_OPTION) {

        try {

            int id_member = Integer.parseInt(
                    tfidmember.getText()
            );

            ControllerMember controller = new ControllerMember();

            controller.hapus(id_member);
            
             controller.tampil(
            (DefaultTableModel) tbmember.getModel()
        );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }     // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
    tfidmember.setText("");
    tfalamat.setText("");
    tftelepon.setText("");
    tfemail.setText("");
    tfpath.setText("");
    tfnik.setText("");

    lbgambar.setIcon(null);

    pathGambar = "";

    tfidmember.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void tbmemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmemberMouseClicked
    int baris = tbmember.getSelectedRow();

    tfidmember.setText(
            tbmember.getValueAt(baris, 0).toString()
    );

    tfalamat.setText(
            tbmember.getValueAt(baris, 1).toString()
    );

    tftelepon.setText(
            tbmember.getValueAt(baris, 2).toString()
    );

    tfemail.setText(
            tbmember.getValueAt(baris, 3).toString()
    );
    
    pathGambar = tbmember.getValueAt(baris, 4).toString();

    tfpath.setText(pathGambar);

    ImageIcon icon = new ImageIcon(
            "Foto_member/" + pathGambar
    );

    Image img = icon.getImage().getScaledInstance(
            lbgambar.getWidth(),
            lbgambar.getHeight(),
            Image.SCALE_SMOOTH
    );

    lbgambar.setIcon(new ImageIcon(img));

    tfnik.setText(
            tbmember.getValueAt(baris, 5).toString()
    );                                                                                                                // TODO add your handling code here:
    }//GEN-LAST:event_tbmemberMouseClicked

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        new FormUtama().setVisible(true);  
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMember().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgambar;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbgambar;
    private javax.swing.JTable tbmember;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfidmember;
    private javax.swing.JTextField tfnik;
    private javax.swing.JTextField tfpath;
    private javax.swing.JTextField tftelepon;
    // End of variables declaration//GEN-END:variables
}
