/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Juan
 */
public class FormUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormUtama.class.getName());

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btmember = new javax.swing.JButton();
        btkategori = new javax.swing.JButton();
        btbarang = new javax.swing.JButton();
        btpenjualan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Utama ");

        btmember.setText("Form Member");
        btmember.addActionListener(this::btmemberActionPerformed);

        btkategori.setText("Form Kategori");
        btkategori.addActionListener(this::btkategoriActionPerformed);

        btbarang.setText("Form Barang");
        btbarang.addActionListener(this::btbarangActionPerformed);

        btpenjualan.setText("Form Penjualan");
        btpenjualan.addActionListener(this::btpenjualanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmember, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btmember)
                .addGap(29, 29, 29)
                .addComponent(btkategori)
                .addGap(29, 29, 29)
                .addComponent(btbarang)
                .addGap(29, 29, 29)
                .addComponent(btpenjualan)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkategoriActionPerformed
        new FormKategori().setVisible(true);  
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_btkategoriActionPerformed

    private void btmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmemberActionPerformed
        new FormMember().setVisible(true);  
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btmemberActionPerformed

    private void btbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbarangActionPerformed
        new FormBarang().setVisible(true);  
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_btbarangActionPerformed

    private void btpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpenjualanActionPerformed
        new FormPenjualan().setVisible(true);  
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_btpenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbarang;
    private javax.swing.JButton btkategori;
    private javax.swing.JButton btmember;
    private javax.swing.JButton btpenjualan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
