/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerBarang;
import Koneksi.koneksi;
import Model.ModelBarang;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Juan
 */
public class FormBarang extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBarang.class.getName());

    /**
     * Creates new form FormBarang
     */
    public FormBarang() {
        initComponents();
        try {

            // format tanggal input
            MaskFormatter mfInput =
                    new MaskFormatter("##/##/####");
            mfInput.install(tftanggalinput);

            // format tanggal update
            MaskFormatter mfUpdate =
                    new MaskFormatter("##/##/####");
            mfUpdate.install(tftanggalupdate);

        } catch (Exception e) {
            e.printStackTrace();
        }

        tampilKategori();

        ControllerBarang controller =
                new ControllerBarang();

        controller.tampil(
                (DefaultTableModel) tbbarang.getModel()
        );
        
        tbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbarangMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfidbarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfmerk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfhargabeli = new javax.swing.JTextField();
        tfhargajual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfsatuan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfstok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tftanggalinput = new javax.swing.JFormattedTextField();
        tftanggalupdate = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        cbidkategori = new javax.swing.JComboBox<>();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbarang = new javax.swing.JTable();
        tfkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Barang");

        jLabel2.setText("ID Barang");

        jLabel3.setText("ID Kategori");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Merk");

        jLabel6.setText("Harga Beli");

        tfhargabeli.addActionListener(this::tfhargabeliActionPerformed);

        jLabel7.setText("Harga Jual");

        jLabel8.setText("Satuan");

        jLabel9.setText("Stok");

        jLabel11.setText("Tanggal Input");

        tftanggalinput.addActionListener(this::tftanggalinputActionPerformed);

        tftanggalupdate.addActionListener(this::tftanggalupdateActionPerformed);

        jLabel12.setText("Tanggal Update");

        cbidkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        tbbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "ID Kategori", "Nama Barang", "Merk", " Harga Beli", "Harga Jual", "Satuan", "Stok", "Tanggal Input", "Tanggal Update"
            }
        ));
        tbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbarang);

        tfkembali.setText("Kembali");
        tfkembali.addActionListener(this::tfkembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(37, 37, 37)
                                                .addComponent(tfidbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfhargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfhargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(30, 30, 30)
                                                .addComponent(cbidkategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tftanggalinput, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tftanggalupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 39, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(tfidbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbidkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttambah)
                            .addComponent(btedit)
                            .addComponent(bthapus)
                            .addComponent(btreset))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfhargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfhargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftanggalinput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftanggalupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(tfkembali)))
                .addGap(123, 123, 123))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tftanggalinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalinputActionPerformed

    private void tftanggalupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalupdateActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
    try {

        // tanggal input
        String[] input =
                tftanggalinput.getText().split("/");

        String tglInputMysql =
                input[2] + "-" +
                input[1] + "-" +
                input[0];

        // tanggal update
        String[] update =
                tftanggalupdate.getText().split("/");

        String tglUpdateMysql =
                update[2] + "-" +
                update[1] + "-" +
                update[0];

        ModelBarang barang = new ModelBarang();

        barang.setId_barang(
                Integer.parseInt(
                        tfidbarang.getText()
                )
        );

        String kategori =
            cbidkategori.getSelectedItem().toString();

        int idKategori =
                Integer.parseInt(
                        kategori.split(" - ")[0]
                );

        barang.setId_kategori(idKategori);

        barang.setNama_barang(
                tfnama.getText()
        );

        barang.setMerk(
                tfmerk.getText()
        );

        barang.setHarga_beli(
                new BigDecimal(
                        tfhargabeli.getText()
                )
        );

        barang.setHarga_jual(
                new BigDecimal(
                        tfhargajual.getText()
                )
        );

        barang.setSatuan_barang(
                tfsatuan.getText()
        );

        barang.setStok(
                Integer.parseInt(
                        tfstok.getText()
                )
        );

        barang.setTgl_input(
                tglInputMysql
        );

        barang.setTgl_update(
                tglUpdateMysql
        );

        ControllerBarang controller =
                new ControllerBarang();

        controller.tambah(barang);

        controller.tampil(
                (DefaultTableModel)
                tbbarang.getModel()
        );

        btresetActionPerformed(null);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal menambah data : "
                + e.getMessage()
        );
    }   // TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
    try {

        // tanggal input
        String[] input =
                tftanggalinput.getText().split("/");

        String tglInputMysql =
                input[2] + "-" +
                input[1] + "-" +
                input[0];

        // tanggal update
        String[] update =
                tftanggalupdate.getText().split("/");

        String tglUpdateMysql =
                update[2] + "-" +
                update[1] + "-" +
                update[0];

        ModelBarang barang = new ModelBarang();

        barang.setId_barang(
                Integer.parseInt(
                        tfidbarang.getText()
                )
        );

        String kategori =
                cbidkategori.getSelectedItem().toString();

        int idKategori =
                Integer.parseInt(
                        kategori.split(" - ")[0]
                );

        barang.setId_kategori(idKategori);

        barang.setNama_barang(
                tfnama.getText()
        );

        barang.setMerk(
                tfmerk.getText()
        );

        barang.setHarga_beli(
                new BigDecimal(
                        tfhargabeli.getText()
                )
        );

        barang.setHarga_jual(
                new BigDecimal(
                        tfhargajual.getText()
                )
        );

        barang.setSatuan_barang(
                tfsatuan.getText()
        );

        barang.setStok(
                Integer.parseInt(
                        tfstok.getText()
                )
        );

        barang.setTgl_input(
                tglInputMysql
        );

        barang.setTgl_update(
                tglUpdateMysql
        );

        ControllerBarang controller =
                new ControllerBarang();

        controller.edit(barang);

        controller.tampil(
                (DefaultTableModel)
                tbbarang.getModel()
        );

        btresetActionPerformed(null);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal mengubah data : "
                + e.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
       int pilihan = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
    );

    if (pilihan == JOptionPane.YES_OPTION) {

        try {

            int id_barang = Integer.parseInt(
                    tfidbarang.getText()
            );

            ControllerBarang controller =
                    new ControllerBarang();

            controller.hapus(id_barang);

            controller.tampil(
                    (DefaultTableModel) tbbarang.getModel()
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        tfidbarang.setText("");
           cbidkategori.setSelectedIndex(0);
           tfnama.setText("");
           tfmerk.setText("");
           tfhargabeli.setText("");
           tfhargajual.setText("");
           tfsatuan.setText("");
           tfstok.setText("");
           tftanggalinput.setText("");
           tftanggalupdate.setText("");

           tfidbarang.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void tfkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkembaliActionPerformed
        new FormUtama().setVisible(true);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_tfkembaliActionPerformed

    private void tbbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbarangMouseClicked
    int baris = tbbarang.getSelectedRow();

    tfidbarang.setText(
            tbbarang.getValueAt(baris, 0).toString()
    );

    cbidkategori.setSelectedItem(
            tbbarang.getValueAt(baris, 1).toString()
    );

    tfnama.setText(
            tbbarang.getValueAt(baris, 2).toString()
    );

    tfmerk.setText(
            tbbarang.getValueAt(baris, 3).toString()
    );

    tfhargabeli.setText(
            tbbarang.getValueAt(baris, 4).toString()
    );

    tfhargajual.setText(
            tbbarang.getValueAt(baris, 5).toString()
    );

    tfsatuan.setText(
            tbbarang.getValueAt(baris, 6).toString()
    );

    tfstok.setText(
            tbbarang.getValueAt(baris, 7).toString()
    );

    tftanggalinput.setText(
            tbbarang.getValueAt(baris, 8).toString()
    );

    tftanggalupdate.setText(
            tbbarang.getValueAt(baris, 9).toString()
    );        // TODO add your handling code here:
    }//GEN-LAST:event_tbbarangMouseClicked

    private void tfhargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargabeliActionPerformed

    private void tampilKategori() {

    try {

        Connection cn = koneksi.getConnection();

        String sql =
        "SELECT * FROM kategori";

        ResultSet rs =
                cn.createStatement().executeQuery(sql);

        cbidkategori.removeAllItems();

        while(rs.next()) {

            cbidkategori.addItem(
                    rs.getInt("id_kategori")
                    + " - " +
                    rs.getString("nama_kategori")
            );
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBarang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JComboBox<String> cbidkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbbarang;
    private javax.swing.JTextField tfhargabeli;
    private javax.swing.JTextField tfhargajual;
    private javax.swing.JTextField tfidbarang;
    private javax.swing.JButton tfkembali;
    private javax.swing.JTextField tfmerk;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfsatuan;
    private javax.swing.JTextField tfstok;
    private javax.swing.JFormattedTextField tftanggalinput;
    private javax.swing.JFormattedTextField tftanggalupdate;
    // End of variables declaration//GEN-END:variables
}
